tags:
  -
    name: data
    description: 'Endpoints that work with data. E.g. importing data and creating data frames for subsequent processing.'
paths:
  /data/save_csv_as_dataframe:
    post:
      operationId: save_csv_as_dataframe
      summary: 'This endpoint saves a web-accessible CSV file as a Pandas DataFrame.'
      tags:
        - data
      responses:
        '200':
          description: 'Returns a response object with ''data_frame_id'' property, which can be used to retrieve data set for subsequent processing.'
          schema:
            x-oad-type: integer
            type: integer
            title: data_frame_id
            description: 'ID of Pandas DataFrame which has been stored in database.'
            format: int32
          x-oad-type: response
      parameters:
        -
          name: csv_url
          in: header
          description: 'The HTTP or HTTPS URL to download the CSV file.'
          required: false
          type: string
          x-oad-type: parameter
    x-oad-type: operation
info:
  title: 'Machine Learning as a Service'
  version: '0.1'
  description: 'A prototype API to provide machine learning functions via REST API (Machine Learning as a Service).'
  contact:
    name: 'Brylie Christopher Oxley'
  license:
    name: 'Creative Commons Zero'
    url: 'https://creativecommons.org/publicdomain/zero/1.0/'
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
swagger: '2.0'
